require('svim.plugin.lsp.lsp')
require('svim.plugin.lsp.lspsaga')

require('svim.plugin.nvim-treesitter')
require('svim.plugin.nvim-tree')
require('svim.plugin.lualine')
require('svim.plugin.dashboard-nvim')
require('svim.plugin.toggleterm')
require('svim.plugin.telescope')
require('svim.plugin.gitsigns')
require('svim.plugin.neodev')
require('svim.plugin.bufferline')
